# Generated by Django 3.0.3 on 2020-02-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productNo', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('clothImgUrl', models.URLField()),
                ('price', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
            ],
        ),
    ]
