# Generated by Django 3.0.3 on 2020-03-03 12:20

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productNo', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('clothImgSuffix', models.CharField(max_length=300)),
                ('price', django_mysql.models.JSONField(default=dict)),
                ('category', models.CharField(max_length=100)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth_Detail_Musinsa',
            fields=[
                ('cloth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cloth.Cloth')),
                ('description', models.TextField(blank=True, null=True)),
                ('season', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('monthlyPopularity', models.CharField(max_length=100)),
                ('detailImageUrlList', django_mysql.models.ListTextField(models.CharField(max_length=200), size=50)),
                ('color', models.CharField(max_length=100)),
                ('importation', models.CharField(max_length=100)),
                ('manufacturingYM', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('sizeNweight', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('manufactured', models.CharField(max_length=100)),
                ('asdirector', models.CharField(max_length=100)),
                ('precautions', models.CharField(max_length=500)),
                ('warrantyBasis', models.CharField(max_length=100)),
            ],
        ),
    ]
