# Generated by Django 3.0.3 on 2020-02-27 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='clothImg',
            new_name='clothImgUrl',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='date',
        ),
        migrations.AddField(
            model_name='cloth',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='description',
            field=models.TextField(blank=True, default='상품 설명', null=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='pageUrl',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
