# Generated by Django 3.0.3 on 2020-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth_detail_musinsa',
            name='detailImageUrlList',
        ),
    ]
