# Generated by Django 3.0.3 on 2020-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_remove_cloth_detail_musinsa_detailimageurllist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth_detail_musinsa',
            name='warrantyBasis',
            field=models.CharField(max_length=200),
        ),
    ]
