# Generated by Django 3.0.3 on 2020-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_auto_20200223_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='clothImg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
